# Generated by Django 4.2.4 on 2023-09-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
    ]
