# Generated by Django 4.2.4 on 2023-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_quitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='imagem',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
